// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'eastus';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .post('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/xplatTestVMQCreate3824/providers/Microsoft.Compute/virtualMachines/xplatvm101/redeploy?api-version=2016-03-30')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Compute/locations/eastus/operations/fb3177d5-d5b1-4b2d-a290-f46202009ee5?monitor=true&api-version=2016-03-30',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Compute/locations/eastus/operations/fb3177d5-d5b1-4b2d-a290-f46202009ee5?api-version=2016-03-30',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'f1952173-7412-4020-8c98-fffca6509750_131097358436124166',
  'x-ms-request-id': 'fb3177d5-d5b1-4b2d-a290-f46202009ee5',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'b5427aa0-0190-402a-807a-f3c4e958bc4c',
  'x-ms-routing-request-id': 'WESTEUROPE:20160820T111241Z:b5427aa0-0190-402a-807a-f3c4e958bc4c',
  date: 'Sat, 20 Aug 2016 11:12:41 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Compute/locations/eastus/operations/fb3177d5-d5b1-4b2d-a290-f46202009ee5?api-version=2016-03-30')
  .reply(200, "{\r\n  \"startTime\": \"2016-08-20T11:12:39.0426907+00:00\",\r\n  \"status\": \"InProgress\",\r\n  \"name\": \"fb3177d5-d5b1-4b2d-a290-f46202009ee5\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '134',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'f1952173-7412-4020-8c98-fffca6509750_131097358436124166',
  'x-ms-request-id': '42245bb9-c9f6-4d7f-9f1b-caf455b2c9ef',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14893',
  'x-ms-correlation-request-id': '6eb97807-cda2-4410-a17b-8ba2197b005f',
  'x-ms-routing-request-id': 'WESTEUROPE:20160820T111312Z:6eb97807-cda2-4410-a17b-8ba2197b005f',
  date: 'Sat, 20 Aug 2016 11:13:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Compute/locations/eastus/operations/fb3177d5-d5b1-4b2d-a290-f46202009ee5?api-version=2016-03-30')
  .reply(200, "{\r\n  \"startTime\": \"2016-08-20T11:12:39.0426907+00:00\",\r\n  \"status\": \"InProgress\",\r\n  \"name\": \"fb3177d5-d5b1-4b2d-a290-f46202009ee5\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '134',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'f1952173-7412-4020-8c98-fffca6509750_131097358436124166',
  'x-ms-request-id': '03d06c94-23c7-4a16-9489-63146664521f',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14957',
  'x-ms-correlation-request-id': '462bac28-742b-44f7-b926-43ee42639d2c',
  'x-ms-routing-request-id': 'WESTEUROPE:20160820T111343Z:462bac28-742b-44f7-b926-43ee42639d2c',
  date: 'Sat, 20 Aug 2016 11:13:42 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/providers/Microsoft.Compute/locations/eastus/operations/fb3177d5-d5b1-4b2d-a290-f46202009ee5?api-version=2016-03-30')
  .reply(200, "{\r\n  \"startTime\": \"2016-08-20T11:12:39.0426907+00:00\",\r\n  \"endTime\": \"2016-08-20T11:14:03.6062268+00:00\",\r\n  \"status\": \"Succeeded\",\r\n  \"name\": \"fb3177d5-d5b1-4b2d-a290-f46202009ee5\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '184',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'f1952173-7412-4020-8c98-fffca6509750_131097358436124166',
  'x-ms-request-id': '0ae03e08-3682-496d-9ecf-200b85859a5c',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14967',
  'x-ms-correlation-request-id': 'a22efdc4-47e6-4990-a319-9610065c09e0',
  'x-ms-routing-request-id': 'WESTEUROPE:20160820T111414Z:a22efdc4-47e6-4990-a319-9610065c09e0',
  date: 'Sat, 20 Aug 2016 11:14:13 GMT' });
 return result; }]];